name: deploy 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Set up build cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install Python dependencies
        run: pip install \
              mkdocs-material
      - name: Deploy Blog
        run: mkdocs gh-deploy --force
